apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-blob-storage
  annotations:
        volume.beta.kubernetes.io/storage-class: azureblob-nfs-premium
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: my-blobstorage
  resources:
    requests:
      storage: 5Gi
