apiVersion: v1
kind: Deployment
metadata:
  name: ubunturequests
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:latest
        resources:
          requests:
            memory: 512Mi
          limits:
            memory: 1Gi
