apiVersion: v1
kind: Pod
metadata:
  name: default-cpu-demo-2
spec:
  containers:
  - name: default-cpu-demo-2-ctr
    image: polinux/stress
    resources:
      limits:
        cpu: "0.4"
      requests:
        cpu: "0.1"
    command: ["stress"]
    args: ["--vm", "1", "--cpu", "1", "--vm-hang", "1"]
