apiVersion: v1
kind: Pod
metadata:
  name: ubuntuts
  labels:
    app: ubuntuts
spec:
  containers:
  - image: jomedei/aksts:latest
    name: ubuntu
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c"]
    args: ["sleep 2592000"]
  restartPolicy: Always
