apiVersion: v1
kind: Pod
metadata:
  name: ubuntuts
  labels:
    app: ubuntuts
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c"]
    args: ["sleep 2592000 && apt-get update & apt-get install -y telnet curl net-tools netcat vim tcpdump wget openssh-client traceroute git python3 python3-pip nmap arping screenfetch htop"]
  restartPolicy: Always
