apiVersion: v1
kind: Pod
metadata:
  name: ubuntutsreq
  labels:
    app: ubuntuts
spec:
  containers:
  - image: jomedei/aksts:latest
    resources:
      requests:
        memory: 512Mi
        cpu: 100m
      limits:
        memory: 1Gi
        cpu: 200m
    name: ubuntu
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c"]
    args: ["sleep 2592000"]
    securityContext:
      privileged: true
  restartPolicy: Always
