apiVersion: v1
kind: Pod
metadata:
  name: ubuntuclean
  labels:
    app: ubuntuclean
spec:
  containers:
  - image: ubuntu
    command:
      - "sleep"
      - "2592000"
    imagePullPolicy: IfNotPresent
    name: ubuntu
  restartPolicy: Always
